"""Deterministic code templates.

Every generated artifact starts from one of these. The LLM may then refine it,
but if the LLM is off, unreachable, or returns garbage, the template output is
still valid, runnable code. Placeholders use __UPPER_SNAKE__ so that Jinja and
f-string braces never collide.
"""

from __future__ import annotations

from typing import Dict

HEADER = """-- Generated by Blast Radius (pre-merge Data Change Firewall)
-- PR: __PR_URL__
-- Change: __CHANGE_NOTE__
-- Severity: __SEVERITY__
-- Downstream at risk: __DOWNSTREAM_NOTE__
-- Review this before merging. It is grounded in the live DataHub schema, not guessed.
"""

MIGRATION_SQL = (
    HEADER
    + """
-- Step 1: add the new column alongside the old one (zero-downtime).
ALTER TABLE __TABLE__
  ADD COLUMN IF NOT EXISTS __NEW_COLUMN__ __COLUMN_TYPE__;

-- Step 2: backfill it from the old column.
UPDATE __TABLE__
   SET __NEW_COLUMN__ = __OLD_COLUMN__
 WHERE __NEW_COLUMN__ IS NULL;

-- Step 3: verify before you cut over. This must return 0.
SELECT count(*) AS unmigrated_rows
  FROM __TABLE__
 WHERE __NEW_COLUMN__ IS NULL
   AND __OLD_COLUMN__ IS NOT NULL;

-- Step 4: only after every downstream consumer below has been updated,
--         drop the old column in a SEPARATE, LATER pull request.
-- __CONSUMER_LIST__
-- ALTER TABLE __TABLE__ DROP COLUMN __OLD_COLUMN__;
"""
)

SHIM_VIEW = (
    HEADER
    + """
-- Compatibility shim: keeps every existing consumer working while they migrate.
-- Point stale consumers at this view, then delete it once the list below is empty.
{{ config(materialized='view') }}

SELECT
    *,
    __NEW_COLUMN__ AS __OLD_COLUMN__   -- deprecated alias, remove after migration
FROM {{ ref('__ASSET__') }}
"""
)

DBT_CONTRACT = """# Generated by Blast Radius. dbt contract + version bump for __ASSET__.
# Enforcing a contract means dbt fails the build on the next silent schema drift,
# instead of a fraud model quietly degrading for six weeks.
version: 2

models:
  - name: __ASSET__
    description: >
      __DESCRIPTION__
    config:
      contract:
        enforced: true
    columns:
__COLUMN_BLOCK__
"""

TESTS_YML = """# Generated by Blast Radius. Tests that would have caught this change.
version: 2

models:
  - name: __ASSET__
    columns:
__TEST_BLOCK__
"""

BACKFILL_DAG = '''"""Backfill DAG generated by Blast Radius.

Change:     __CHANGE_NOTE__
Downstream: __DOWNSTREAM_NOTE__
PR:         __PR_URL__

Column names and types below come from DataHub list_schema_fields, not from a
guess, which is why this runs on the first try.
"""

from datetime import datetime, timedelta

from airflow import DAG
from airflow.operators.empty import EmptyOperator
from airflow.providers.common.sql.operators.sql import SQLExecuteQueryOperator

DEFAULT_ARGS = {
    "owner": "data-platform",
    "retries": 2,
    "retry_delay": timedelta(minutes=5),
    "depends_on_past": False,
}

# Assets that must be re-materialised after this change lands.
DOWNSTREAM_ASSETS = __DOWNSTREAM_JSON__

with DAG(
    dag_id="__DAG_ID__",
    description="Blast Radius backfill for __ASSET__",
    default_args=DEFAULT_ARGS,
    start_date=datetime(__DATE__),
    schedule=None,
    catchup=False,
    max_active_runs=1,
    tags=["blast-radius", "backfill", "generated"],
) as dag:

    start = EmptyOperator(task_id="start")

    backfill = SQLExecuteQueryOperator(
        task_id="backfill___ASSET__",
        conn_id="warehouse",
        sql="""
__SELECT__
""",
    )

    verify = SQLExecuteQueryOperator(
        task_id="verify_no_nulls",
        conn_id="warehouse",
        sql="""
SELECT count(*) AS bad_rows
  FROM __TABLE__
 WHERE __VERIFY_COLUMN__ IS NULL
""",
    )

    done = EmptyOperator(task_id="done")

    start >> backfill >> verify >> done
'''


def render(template: str, values: Dict[str, str]) -> str:
    """Replace __PLACEHOLDER__ tokens. Unknown tokens are left visible on
    purpose so a human notices instead of shipping a silent blank."""
    out = template
    for key, value in values.items():
        out = out.replace("__" + key.upper() + "__", str(value))
    return out
