"""[4] Remediation Agent - write the fix, grounded in the real catalog schema.

The code-gen thesis from the brief: generated code must use the *actual*
column names and types from list_schema_fields, not names the model invented.
So every artifact is templated from live schema first, and only then handed to
the LLM for refinement. If the LLM is off or fails, the template output ships
as-is and is still valid, runnable code.

Artifacts produced:
  001_migration.sql        expand / backfill / verify / contract-drop
  <asset>__compat.sql      deprecation shim view so nothing breaks today
  <asset>_contract.yml     dbt contract + version bump
  backfill_<slug>_dag.py   Airflow DAG to re-materialise downstream
  <asset>_tests.yml        the tests that would have caught this
"""

from __future__ import annotations

import logging
import re
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional

from ..context.base import ML_TYPES, parse_dataset_urn
from ..llm import extract_code
from ..severity import severity_at_least
from ..state import BlastRadiusState, ChangedAsset, ColumnChange, GeneratedArtifact
from ..templates import BACKFILL_DAG, DBT_CONTRACT, MIGRATION_SQL, SHIM_VIEW, TESTS_YML, render

log = logging.getLogger("blast_radius.remediate")

SYSTEM_PROMPT = (
    "You are a senior analytics engineer generating production migration code. "
    "You are given the real catalog schema. Use only those column names and types. "
    "Never invent a column. Return only code, no prose, no explanation, no markdown fences "
    "unless asked. The code must run as-is."
)


def _slug(text: str) -> str:
    return re.sub(r"[^a-z0-9]+", "_", (text or "change").lower()).strip("_")[:40] or "change"


def _table_name(urn: Optional[str], fallback: str) -> str:
    parsed = parse_dataset_urn(urn or "")
    if parsed:
        return parsed[1]
    return fallback


def _column_type(fields, column: str, default: str = "VARCHAR") -> str:
    for field in fields or []:
        if field.name.lower() == (column or "").lower():
            return (field.native_type or field.type or default).upper()
    return default


def _consumer_lines(state: BlastRadiusState, limit: int = 8) -> List[str]:
    lines: List[str] = []
    for item in sorted(state.impacted, key=lambda i: -i.score)[:limit]:
        owners = ", ".join(item.entity.owners[:2]) or "UNOWNED"
        lines.append(
            "%s (%s, owner: %s)" % (item.entity.short_name, item.entity.entity_type, owners)
        )
    return lines


def _downstream_note(state: BlastRadiusState) -> str:
    ml = [i.entity.short_name for i in state.impacted if i.entity.entity_type in ML_TYPES]
    bi = [i.entity.short_name for i in state.impacted if i.entity.entity_type in ("dashboard", "chart")]
    bits: List[str] = []
    if ml:
        bits.append("ML: " + ", ".join(ml[:4]))
    if bi:
        bits.append("BI: " + ", ".join(bi[:4]))
    return " | ".join(bits) or "no catalogued consumers"


def _change_note(changes: List[ColumnChange]) -> str:
    return "; ".join(c.describe().replace("`", "") for c in changes[:4]) or "schema change"


def _refine(deps, purpose: str, template_output: str, schema_block: str, context_block: str) -> Optional[str]:
    llm = deps.llm
    if not llm or not llm.enabled:
        return None
    prompt = "\n".join(
        [
            "TASK: " + purpose,
            "",
            "REAL CATALOG SCHEMA (authoritative - use these exact names and types):",
            schema_block or "(schema unavailable; keep the template's column names)",
            "",
            "CONTEXT:",
            context_block,
            "",
            "STARTING POINT (already valid; improve it, do not regress it):",
            template_output,
            "",
            "Return the complete improved file. Keep every comment header line that "
            "starts with 'Generated by Blast Radius'. Do not add explanation.",
        ]
    )
    try:
        raw = llm.complete(SYSTEM_PROMPT, prompt, max_tokens=1800)
    except Exception as exc:
        log.warning("LLM refinement failed for %s: %s", purpose, exc)
        deps.notes.append("LLM code refinement unavailable: %s" % str(exc)[:120])
        return None
    code = extract_code(raw)
    if not code or len(code) < 40:
        return None
    return code


def _schema_block(fields) -> str:
    lines = []
    for field in (fields or [])[:40]:
        flag = " PRIMARY KEY" if field.is_primary_key else ("" if field.nullable else " NOT NULL")
        lines.append("  %s %s%s" % (field.name, field.native_type or field.type or "?", flag))
    return "\n".join(lines)


def _primary_change(asset: ChangedAsset) -> Optional[ColumnChange]:
    breaking = asset.breaking_changes
    if breaking:
        order = {"drop": 0, "rename": 1, "type_change": 2, "nullability": 3}
        return sorted(breaking, key=lambda c: order.get(c.kind, 9))[0]
    return asset.changes[0] if asset.changes else None


def remediate(state: BlastRadiusState, deps) -> Dict[str, Any]:
    settings = deps.settings
    policy = settings.section("remediation")
    ctx = deps.ctx
    artifacts: List[GeneratedArtifact] = list(state.artifacts)

    threshold = str(policy.get("min_severity", "HIGH")).upper()
    if not severity_at_least(state.severity, threshold):
        log.info("severity %s below %s; skipping remediation", state.severity, threshold)
        return {"artifacts": artifacts}

    consumers = _consumer_lines(state)
    downstream_note = _downstream_note(state)
    downstream_names = [i.entity.short_name for i in sorted(state.impacted, key=lambda x: -x.score)][:12]
    today = datetime.now(timezone.utc)

    for asset in state.changed_assets:
        change = _primary_change(asset)
        if change is None:
            continue
        if not asset.breaking_changes and state.severity != "CRITICAL":
            continue

        fields = []
        if asset.urn:
            try:
                fields = ctx.list_schema_fields(asset.urn)
            except Exception as exc:
                log.debug("list_schema_fields failed for %s: %s", asset.urn, exc)

        table = _table_name(asset.urn, asset.name)
        slug = _slug(asset.name + "_" + change.kind + "_" + (change.column or ""))
        directory = "blast-radius/" + slug
        old_column = change.column
        new_column = change.new_column or (change.column + "_v2")
        column_type = _column_type(fields, change.column, "VARCHAR")
        change_note = _change_note(asset.changes)
        schema_block = _schema_block(fields)
        context_block = "\n".join(
            [
                "Asset: " + asset.name + " (" + asset.asset_type + ")",
                "URN: " + (asset.urn or "unresolved"),
                "Change: " + change_note,
                "Severity: " + state.severity,
                "Downstream consumers:",
                "\n".join("  - " + line for line in consumers) or "  - none",
            ]
        )

        shared = {
            "PR_URL": settings.pr_url() or "(local run)",
            "CHANGE_NOTE": change_note,
            "SEVERITY": state.severity,
            "DOWNSTREAM_NOTE": downstream_note,
            "TABLE": table,
            "ASSET": asset.name,
            "OLD_COLUMN": old_column,
            "NEW_COLUMN": new_column,
            "COLUMN_TYPE": change.new_type or column_type,
            "CONSUMER_LIST": "Consumers to migrate first: " + ("; ".join(consumers) or "none"),
        }

        # -- migration SQL ------------------------------------------------
        if policy.get("emit_migration_sql", True) and change.kind in ("rename", "drop", "type_change"):
            base = render(MIGRATION_SQL, shared)
            refined = _refine(
                deps,
                "Produce a zero-downtime warehouse migration for a " + change.kind + " on "
                + table + "." + str(old_column) + ". Keep the expand/backfill/verify/contract phases separate.",
                base,
                schema_block,
                context_block,
            )
            artifacts.append(
                GeneratedArtifact(
                    path=directory + "/001_migration.sql",
                    language="sql",
                    purpose="Zero-downtime migration for " + change.describe().replace("`", ""),
                    content=refined or base,
                    generated_by="llm+template" if refined else "template",
                    for_asset=asset.name,
                )
            )

        # -- compatibility shim view ---------------------------------------
        if policy.get("emit_shim_view", True) and change.kind == "rename":
            base = render(SHIM_VIEW, shared)
            artifacts.append(
                GeneratedArtifact(
                    path=directory + "/" + asset.name + "__compat.sql",
                    language="sql",
                    purpose="Deprecation shim: keeps " + str(old_column) + " working during migration",
                    content=base,
                    generated_by="template",
                    for_asset=asset.name,
                )
            )

        # -- dbt contract ---------------------------------------------------
        if policy.get("emit_dbt_contract", True) and asset.asset_type in ("dbt_model", "sql", "dbt_contract"):
            column_lines: List[str] = []
            renamed = {c.column: c.new_column for c in asset.changes if c.kind == "rename"}
            dropped = {c.column for c in asset.changes if c.kind == "drop"}
            for field in (fields or [])[:40]:
                if field.name in dropped:
                    continue
                name = renamed.get(field.name, field.name)
                column_lines.append("      - name: " + name)
                column_lines.append(
                    "        data_type: " + (field.native_type or field.type or "varchar").lower()
                )
                if field.description:
                    column_lines.append(
                        '        description: "' + field.description.replace('"', "'")[:160] + '"'
                    )
                if not field.nullable or field.is_primary_key:
                    column_lines.append("        constraints:")
                    column_lines.append("          - type: not_null")
            if not column_lines and change.new_column:
                column_lines = [
                    "      - name: " + str(new_column),
                    "        data_type: " + column_type.lower(),
                ]
            contract = render(
                DBT_CONTRACT,
                {
                    "ASSET": asset.name,
                    "DESCRIPTION": "Contract enforced by Blast Radius after " + change_note
                    + ". Downstream at risk: " + downstream_note + ".",
                    "COLUMN_BLOCK": "\n".join(column_lines) or "      []",
                },
            )
            artifacts.append(
                GeneratedArtifact(
                    path=directory + "/" + asset.name + "_contract.yml",
                    language="yaml",
                    purpose="dbt contract + version bump so the next drift fails the build",
                    content=contract,
                    generated_by="template",
                    for_asset=asset.name,
                )
            )

        # -- backfill DAG ---------------------------------------------------
        if policy.get("emit_backfill_dag", True):
            select_columns = []
            for field in (fields or [])[:30]:
                if field.name == old_column and change.kind == "rename":
                    select_columns.append("    " + field.name + " AS " + str(new_column))
                elif field.name == old_column and change.kind == "drop":
                    continue
                else:
                    select_columns.append("    " + field.name)
            if not select_columns:
                select_columns = ["    *"]
            select_sql = (
                "INSERT OVERWRITE " + table + "\nSELECT\n"
                + ",\n".join(select_columns)
                + "\nFROM " + table + "\nWHERE 1 = 1"
            )
            dag = render(
                BACKFILL_DAG,
                {
                    "DAG_ID": "blast_radius_backfill_" + slug,
                    "TABLE": table,
                    "ASSET": asset.name,
                    "DATE": "%d, %d, %d" % (today.year, today.month, today.day),
                    "SELECT": select_sql,
                    "DOWNSTREAM_NOTE": downstream_note,
                    "CHANGE_NOTE": change_note,
                    "DOWNSTREAM_JSON": repr(downstream_names),
                    "PR_URL": settings.pr_url() or "(local run)",
                    "VERIFY_COLUMN": str(new_column if change.kind == "rename" else old_column),
                },
            )
            artifacts.append(
                GeneratedArtifact(
                    path=directory + "/backfill_" + slug + "_dag.py",
                    language="python",
                    purpose="Airflow backfill so downstream tables are re-materialised",
                    content=dag,
                    generated_by="template",
                    for_asset=asset.name,
                )
            )

        # -- tests ------------------------------------------------------------
        if policy.get("emit_tests", True):
            test_lines: List[str] = []
            target = str(new_column if change.kind == "rename" else old_column)
            test_lines.append("      - name: " + target)
            test_lines.append("        data_tests:")
            test_lines.append("          - not_null")
            if any(f.is_primary_key and f.name == target for f in fields or []):
                test_lines.append("          - unique")
            for item in state.impacted:
                if item.entity.entity_type in ML_TYPES and item.impacted_columns:
                    test_lines.append(
                        "          # feeds ML asset " + item.entity.short_name
                        + " via " + ", ".join(item.impacted_columns[:2])
                    )
                    break
            tests = render(
                TESTS_YML, {"ASSET": asset.name, "TEST_BLOCK": "\n".join(test_lines)}
            )
            artifacts.append(
                GeneratedArtifact(
                    path=directory + "/" + asset.name + "_tests.yml",
                    language="yaml",
                    purpose="Tests that would have caught this change before merge",
                    content=tests,
                    generated_by="template",
                    for_asset=asset.name,
                )
            )

    log.info("generated %d artifacts", len(artifacts))
    return {"artifacts": artifacts}
